services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: eventsphere
      POSTGRES_PASSWORD: eventsphere
      POSTGRES_DB: eventsphere
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U eventsphere']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/meili_data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://eventsphere:eventsphere@postgres:5432/eventsphere?schema=public
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: dev-access-secret-min-32-characters-long
      JWT_REFRESH_SECRET: dev-refresh-secret-min-32-characters-long
      API_PORT: 4000
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_WS_URL: http://localhost:4000
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  meili_data:
